Repository re-prife/back-end, pull requests merged in 2022-06, with the labels that each got.

#107 #106 DTO 기본 생성자 추가
  src/main/java/kr/hs/mirim/family/dto/request/LoginUserRequest.java
  src/main/java/kr/hs/mirim/family/dto/response/LoginUserResponse.java
Labels: 버그🐞

#110 develop -> main
  src/main/java/kr/hs/mirim/family/dto/request/LoginUserRequest.java
  src/main/java/kr/hs/mirim/family/dto/response/LoginUserResponse.java
Labels: 배포☁

#113 #111 회원이 그룹에 가입되어있는지 확인
  src/main/java/kr/hs/mirim/family/service/UserService.java
Labels: 버그🐞, 기능 : 회원/그룹 💡

#114 #112 비밀번호의 최소길이 확인
  src/main/java/kr/hs/mirim/family/dto/request/CreateUserRequest.java
  src/main/java/kr/hs/mirim/family/dto/request/UpdateUserPasswordRequest.java
Labels: 버그🐞, 기능 : 회원/그룹 💡

#123 #122 그룹 가입 / 생성 시 그룹 초대 코드 반환하기
  src/main/java/kr/hs/mirim/family/controller/GroupController.java
  src/main/java/kr/hs/mirim/family/dto/response/GroupResponse.java
  src/main/java/kr/hs/mirim/family/service/GroupService.java
Labels: 버그🐞, 기능 : 회원/그룹 💡

#125 #124 codecov의 controller, service 범위 지정
  build.gradle
Labels: 테스트 💯

#101 #100 이미지 관련 기능 구현
  build.gradle
  src/main/java/kr/hs/mirim/family/config/MultipartConfig.java
  src/main/java/kr/hs/mirim/family/config/WebConfig.java
  src/main/java/kr/hs/mirim/family/controller/ImageController.java
  src/main/java/kr/hs/mirim/family/dto/request/UpdateUserRequest.java
  src/main/java/kr/hs/mirim/family/dto/response/IngredientListResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/LoginUserResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/UserFindResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/UserListResponse.java
  src/main/java/kr/hs/mirim/family/entity/ingredient/Ingredient.java
  src/main/java/kr/hs/mirim/family/entity/ingredient/repository/IngredientRepository.java
  src/main/java/kr/hs/mirim/family/entity/ingredient/repository/IngredientRepositoryImpl.java
  src/main/java/kr/hs/mirim/family/entity/user/User.java
  src/main/java/kr/hs/mirim/family/entity/user/repository/UserRepository.java
  src/main/java/kr/hs/mirim/family/entity/user/repository/UserRepositoryImpl.java
  src/main/java/kr/hs/mirim/family/service/ImageService.java
  src/main/java/kr/hs/mirim/family/service/IngredientService.java
  src/main/java/kr/hs/mirim/family/service/UserService.java
  src/main/resources/application.yml
  src/test/java/kr/hs/mirim/family/FamilyApplicationTests.java
Labels: 기능 : 회원/그룹 💡, 기능 : 식재료 💡

#129 #128 login시 이미지경로를 반환하는 기능
  src/main/java/kr/hs/mirim/family/service/UserService.java
Labels: 기능 : 회원/그룹 💡, 리팩토링 ✍

#130 Release 2.0 -> main
  build.gradle
  src/main/java/kr/hs/mirim/family/config/MultipartConfig.java
  src/main/java/kr/hs/mirim/family/config/WebConfig.java
  src/main/java/kr/hs/mirim/family/controller/GroupController.java
  src/main/java/kr/hs/mirim/family/controller/ImageController.java
  src/main/java/kr/hs/mirim/family/dto/request/UpdateUserRequest.java
  src/main/java/kr/hs/mirim/family/dto/response/GroupResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/IngredientListResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/LoginUserResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/UserFindResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/UserListResponse.java
  src/main/java/kr/hs/mirim/family/entity/ingredient/Ingredient.java
  src/main/java/kr/hs/mirim/family/entity/ingredient/repository/IngredientRepository.java
  src/main/java/kr/hs/mirim/family/entity/ingredient/repository/IngredientRepositoryImpl.java
  src/main/java/kr/hs/mirim/family/entity/user/User.java
  src/main/java/kr/hs/mirim/family/entity/user/repository/UserRepository.java
  src/main/java/kr/hs/mirim/family/entity/user/repository/UserRepositoryImpl.java
  src/main/java/kr/hs/mirim/family/service/GroupService.java
  src/main/java/kr/hs/mirim/family/service/ImageService.java
  src/main/java/kr/hs/mirim/family/service/IngredientService.java
  src/main/java/kr/hs/mirim/family/service/UserService.java
  src/main/resources/application.yml
  src/test/java/kr/hs/mirim/family/FamilyApplicationTests.java
Labels: 배포☁

#126 #124 codecov의 controller, service 범위 지정
  build.gradle
Labels: 테스트 💯

#135 #134 집안일 응답 관련 기능 처리
  src/main/java/kr/hs/mirim/family/controller/ChoreController.java
  src/main/java/kr/hs/mirim/family/dto/response/ChoreListMonthResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/ChoreListOneDayResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/ChoreListResponse.java
  src/main/java/kr/hs/mirim/family/entity/chore/repository/ChoreRepositoryExtension.java
  src/main/java/kr/hs/mirim/family/entity/chore/repository/ChoreRepositoryImpl.java
  src/main/java/kr/hs/mirim/family/service/ChoreService.java
Labels: 버그🐞, 기능 : 집안일 💡

#141 #139 회원 상세 조회 날짜 기능 수정
  src/main/java/kr/hs/mirim/family/service/UserService.java
Labels: 버그🐞, 기능 : 회원/그룹 💡

#150 #120 심부름 생성 시 그룹원에게 알림을 보내는 기능
  src/main/java/kr/hs/mirim/family/controller/NotificationController.java
  src/main/java/kr/hs/mirim/family/controller/QuestController.java
  src/main/java/kr/hs/mirim/family/dto/response/QuestNotificationResponse.java
  src/main/java/kr/hs/mirim/family/entity/Notification/Notification.java
  src/main/java/kr/hs/mirim/family/entity/Notification/repository/EmitterRepository.java
  src/main/java/kr/hs/mirim/family/entity/Notification/repository/EmitterRepositoryImpl.java
  src/main/java/kr/hs/mirim/family/entity/Notification/repository/NotificationRepository.java
  src/main/java/kr/hs/mirim/family/service/NotificationService.java
  src/main/java/kr/hs/mirim/family/service/QuestService.java
Labels: 기능 : 심부름💡

#161 [5차 스프린트 배포] develop -> release 3.0
  build.gradle
  src/main/java/kr/hs/mirim/family/config/MultipartConfig.java
  src/main/java/kr/hs/mirim/family/controller/ChoreController.java
  src/main/java/kr/hs/mirim/family/controller/GroupController.java
  src/main/java/kr/hs/mirim/family/controller/NotificationController.java
  src/main/java/kr/hs/mirim/family/controller/QuestController.java
  src/main/java/kr/hs/mirim/family/dto/response/ChoreNotificationResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/GetGroupReportResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/GroupResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/IngredientListResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/QuestNotificationResponse.java
  src/main/java/kr/hs/mirim/family/entity/notification/Notification.java
  src/main/java/kr/hs/mirim/family/entity/notification/repository/EmitterRepository.java
  src/main/java/kr/hs/mirim/family/entity/notification/repository/EmitterRepositoryImpl.java
  src/main/java/kr/hs/mirim/family/entity/notification/repository/NotificationRepository.java
  src/main/java/kr/hs/mirim/family/exception/InternalServerException.java
  src/main/java/kr/hs/mirim/family/service/GroupService.java
  src/main/java/kr/hs/mirim/family/service/ImageService.java
  src/main/java/kr/hs/mirim/family/service/KingService.java
  src/main/java/kr/hs/mirim/family/service/NotificationService.java
  src/main/java/kr/hs/mirim/family/service/QuestService.java
  src/main/resources/application.yml
  src/test/java/kr/hs/mirim/family/controller/KingControllerTest.java
  src/test/resources/application.yml
  src/test/resources/data.sql
Labels: 배포☁

#162 Release 3.0 -> main
  build.gradle
  src/main/java/kr/hs/mirim/family/config/MultipartConfig.java
  src/main/java/kr/hs/mirim/family/controller/ChoreController.java
  src/main/java/kr/hs/mirim/family/controller/GroupController.java
  src/main/java/kr/hs/mirim/family/controller/NotificationController.java
  src/main/java/kr/hs/mirim/family/controller/QuestController.java
  src/main/java/kr/hs/mirim/family/dto/response/ChoreNotificationResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/GetGroupReportResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/GroupResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/IngredientListResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/QuestNotificationResponse.java
  src/main/java/kr/hs/mirim/family/entity/notification/Notification.java
  src/main/java/kr/hs/mirim/family/entity/notification/repository/EmitterRepository.java
  src/main/java/kr/hs/mirim/family/entity/notification/repository/EmitterRepositoryImpl.java
  src/main/java/kr/hs/mirim/family/entity/notification/repository/NotificationRepository.java
  src/main/java/kr/hs/mirim/family/exception/InternalServerException.java
  src/main/java/kr/hs/mirim/family/service/GroupService.java
  src/main/java/kr/hs/mirim/family/service/ImageService.java
  src/main/java/kr/hs/mirim/family/service/KingService.java
  src/main/java/kr/hs/mirim/family/service/NotificationService.java
  src/main/java/kr/hs/mirim/family/service/QuestService.java
  src/main/resources/application.yml
  src/test/java/kr/hs/mirim/family/controller/KingControllerTest.java
  src/test/resources/application.yml
  src/test/resources/data.sql
Labels: 배포☁

#165 #103 심부름 Controller 통합 테스트 작성 완료
  src/main/java/kr/hs/mirim/family/controller/QuestController.java
  src/main/java/kr/hs/mirim/family/service/QuestService.java
  src/test/java/kr/hs/mirim/family/controller/QuestControllerTest.java
  src/test/resources/application.yml
  src/test/resources/data.sql
Labels: 테스트 💯, 기능 : 심부름💡

#164 #163 이미지 확장자 고정 처리
  src/main/java/kr/hs/mirim/family/service/ImageService.java
Labels: 버그🐞

#131 #104 User Controller 통합테스트 코드 작성
  .github/workflows/gradle.yml
  src/main/java/kr/hs/mirim/family/dto/response/UserKingResponse.java
  src/main/java/kr/hs/mirim/family/service/UserService.java
  src/test/java/kr/hs/mirim/family/controller/UserControllerTest.java
  src/test/resources/application.yml
  src/test/resources/data.sql
Labels: 테스트 💯, 기능 : 회원/그룹 💡

#167 #166 로그인시, 그룹 초대 코드를 반환하는 기능
  src/main/java/kr/hs/mirim/family/dto/response/LoginUserResponse.java
  src/main/java/kr/hs/mirim/family/service/UserService.java
Labels: 버그🐞, 기능 : 회원/그룹 💡

#153 #105 Chore controller 통합테스트
  src/main/java/kr/hs/mirim/family/service/ChoreService.java
  src/test/java/kr/hs/mirim/family/controller/ChoreControllerTest.java
  src/test/resources/data.sql
Labels: 테스트 💯, 기능 : 집안일 💡

#158 #157 이미지 컨트롤러 테스트 코드 작성
  src/test/java/kr/hs/mirim/family/controller/ImageControllerTest.java
  src/test/resources/image/test.png
Labels: 테스트 💯

#173 #169 로그인 시 그룹에 가입하지 않은 회원, 그룹 null 반환 처리
  src/main/java/kr/hs/mirim/family/service/UserService.java
Labels: 버그🐞

#177 Hotfix-3.3 -> Main
  src/main/java/kr/hs/mirim/family/controller/IngredientController.java
  src/main/java/kr/hs/mirim/family/dto/response/IngredientIdResponse.java
  src/main/java/kr/hs/mirim/family/service/IngredientService.java
Labels: 배포☁

#180 #179 그룹없는 회원 로그인 기능 수정으로 인한 테스트 코드 변경
  src/test/java/kr/hs/mirim/family/controller/UserControllerTest.java
Labels: 테스트 💯, 기능 : 회원/그룹 💡, 리팩토링 ✍

#184 #183 심부름 상세 조회 시 심부름의 내용도 함께 반환
  src/main/java/kr/hs/mirim/family/dto/response/QuestFindOneResponse.java
  src/main/java/kr/hs/mirim/family/service/QuestService.java
Labels: 기능 : 심부름💡, 리팩토링 ✍

#185 #181 집안일 인증 SSE 리펙토링
  src/main/java/kr/hs/mirim/family/controller/NotificationController.java
  src/main/java/kr/hs/mirim/family/dto/response/ChoreCertifyReactionNotificationResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/ChoreCertifyRequestNotificationResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/ChoreListResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/ChoreNotificationResponse.java
  src/main/java/kr/hs/mirim/family/entity/chore/repository/ChoreRepositoryImpl.java
  src/main/java/kr/hs/mirim/family/service/ChoreService.java
  src/main/java/kr/hs/mirim/family/service/NotificationService.java
  src/test/java/kr/hs/mirim/family/controller/ChoreControllerTest.java
Labels: 기능 : 집안일 💡, 리팩토링 ✍

#186 Release 4.0 -> Main
  .github/workflows/gradle.yml
  src/main/java/kr/hs/mirim/family/controller/GroupController.java
  src/main/java/kr/hs/mirim/family/controller/IngredientController.java
  src/main/java/kr/hs/mirim/family/controller/NotificationController.java
  src/main/java/kr/hs/mirim/family/controller/QuestController.java
  src/main/java/kr/hs/mirim/family/custom/CustomCollectionValidator.java
  src/main/java/kr/hs/mirim/family/dto/request/QuestRequest.java
  src/main/java/kr/hs/mirim/family/dto/request/UpdateIngredientCountRequest.java
  src/main/java/kr/hs/mirim/family/dto/response/ChoreCertifyReactionNotificationResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/ChoreCertifyRequestNotificationResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/ChoreListResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/ChoreNotificationResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/QuestFindOneResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/QuestNotificationResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/UserKingResponse.java
  src/main/java/kr/hs/mirim/family/entity/chore/repository/ChoreRepositoryImpl.java
  src/main/java/kr/hs/mirim/family/entity/group/repository/GroupRepository.java
  src/main/java/kr/hs/mirim/family/entity/user/repository/UserRepository.java
  src/main/java/kr/hs/mirim/family/service/ChoreService.java
  src/main/java/kr/hs/mirim/family/service/GroupService.java
  src/main/java/kr/hs/mirim/family/service/ImageService.java
  src/main/java/kr/hs/mirim/family/service/IngredientService.java
  src/main/java/kr/hs/mirim/family/service/NotificationService.java
  src/main/java/kr/hs/mirim/family/service/QuestService.java
  src/main/java/kr/hs/mirim/family/service/UserService.java
  src/test/java/kr/hs/mirim/family/FamilyApplicationTests.java
  src/test/java/kr/hs/mirim/family/controller/ChoreControllerTest.java
  src/test/java/kr/hs/mirim/family/controller/GroupControllerTest.java
  src/test/java/kr/hs/mirim/family/controller/ImageControllerTest.java
  src/test/java/kr/hs/mirim/family/controller/IngredientControllerTest.java
  src/test/java/kr/hs/mirim/family/controller/QuestControllerTest.java
  src/test/java/kr/hs/mirim/family/controller/UserControllerTest.java
  src/test/resources/application.yml
  src/test/resources/data.sql
  src/test/resources/image/test.png
Labels: 배포☁

#195 #192 심부름 생성 시 심부름 ID 반환
  src/main/java/kr/hs/mirim/family/controller/QuestController.java
  src/main/java/kr/hs/mirim/family/dto/request/QuestRequest.java
  src/main/java/kr/hs/mirim/family/dto/response/QuestIdResponse.java
  src/main/java/kr/hs/mirim/family/service/QuestService.java
  src/test/java/kr/hs/mirim/family/controller/QuestControllerTest.java
Labels: 버그🐞, 기능 : 심부름💡

#197 #196 집안일 응답시, 집안일 당번 아이디 반환하는 기능
  src/main/java/kr/hs/mirim/family/controller/ChoreController.java
  src/main/java/kr/hs/mirim/family/dto/response/ChoreCertifyReactionResponse.java
  src/main/java/kr/hs/mirim/family/service/ChoreService.java
Labels: 버그🐞, 기능 : 집안일 💡

#198 Hotfix4.1.2 -> Main
  src/main/java/kr/hs/mirim/family/controller/ChoreController.java
  src/main/java/kr/hs/mirim/family/dto/response/ChoreCertifyReactionResponse.java
  src/main/java/kr/hs/mirim/family/service/ChoreService.java
Labels: 배포☁

#201 Hotfix4.2 -> Main
  src/main/java/kr/hs/mirim/family/service/IngredientService.java
Labels: 배포☁

#204 #203 이달의 왕의 아이디와 이름이 맞지 않는 문제 수정
  src/main/java/kr/hs/mirim/family/entity/quest/repository/QuestRepositoryImpl.java
Labels: 버그🐞

#205 Hotfix4.2.1 -> Main
  src/main/java/kr/hs/mirim/family/entity/quest/repository/QuestRepositoryImpl.java
Labels: 배포☁

#206 Release-5.0 -> Main
  src/main/resources/application.yml
Labels: 배포☁
