Repository re-prife/back-end, pull requests merged in 2022-04, with the labels that each got.

#29 #28 REST API 예외 처리
  src/main/java/kr/hs/mirim/family/exception/DataNotFoundException.java
  src/main/java/kr/hs/mirim/family/exception/handler/ApiException.java
  src/main/java/kr/hs/mirim/family/exception/handler/ApiExceptionAdvice.java
  src/main/java/kr/hs/mirim/family/exception/handler/ErrorResponse.java
Labels: 세팅 ⚙

#30 #22 그룹 생성 기능 구현
  src/main/java/kr/hs/mirim/family/controller/GroupController.java
  src/main/java/kr/hs/mirim/family/dto/request/CreateGroupRequest.java
  src/main/java/kr/hs/mirim/family/entity/group/Group.java
  src/main/java/kr/hs/mirim/family/entity/group/repository/GroupRepository.java
  src/main/java/kr/hs/mirim/family/entity/user/User.java
  src/main/java/kr/hs/mirim/family/entity/user/repository/UserRepository.java
  src/main/java/kr/hs/mirim/family/exception/FormValidateException.java
  src/main/java/kr/hs/mirim/family/service/GroupService.java
Labels: 기능 : 회원/그룹 💡

#27 #15 회원가입 기능 구현
  build.gradle
  src/main/java/kr/hs/mirim/family/config/SecureConfig.java
  src/main/java/kr/hs/mirim/family/controller/UserController.java
  src/main/java/kr/hs/mirim/family/dto/request/UserSignUpDto.java
  src/main/java/kr/hs/mirim/family/entity/user/User.java
  src/main/java/kr/hs/mirim/family/entity/user/repository/UserRepository.java
  src/main/java/kr/hs/mirim/family/exception/AlreadyExistsException.java
  src/main/java/kr/hs/mirim/family/service/UserService.java
Labels: 기능 : 회원/그룹 💡

#32 #23 그룹 가입 기능
  src/main/java/kr/hs/mirim/family/controller/GroupController.java
  src/main/java/kr/hs/mirim/family/dto/request/JoinGroupRequest.java
  src/main/java/kr/hs/mirim/family/entity/group/repository/GroupRepository.java
  src/main/java/kr/hs/mirim/family/service/GroupService.java
Labels: 기능 : 회원/그룹 💡

#34 #33 회원 생성 기능 관련 리펙토링
  src/main/java/kr/hs/mirim/family/controller/UserController.java
  src/main/java/kr/hs/mirim/family/dto/request/CreateUserRequest.java
  src/main/java/kr/hs/mirim/family/entity/user/User.java
  src/main/java/kr/hs/mirim/family/service/UserService.java
Labels: 기능 : 회원/그룹 💡, 리팩토링 ✍

#35 #24 그룹에 속한 유저 목록 반환 기능
  build.gradle
  src/main/java/kr/hs/mirim/family/config/QueryDslConfig.java
  src/main/java/kr/hs/mirim/family/controller/GroupController.java
  src/main/java/kr/hs/mirim/family/dto/response/UserListResponse.java
  src/main/java/kr/hs/mirim/family/entity/group/repository/GroupRepository.java
  src/main/java/kr/hs/mirim/family/entity/group/repository/GroupRepositoryExtension.java
  src/main/java/kr/hs/mirim/family/entity/group/repository/GroupRepositoryImpl.java
  src/main/java/kr/hs/mirim/family/entity/user/repository/UserRepository.java
  src/main/java/kr/hs/mirim/family/entity/user/repository/UserRepositoryExtension.java
  src/main/java/kr/hs/mirim/family/entity/user/repository/UserRepositoryImpl.java
  src/main/java/kr/hs/mirim/family/service/GroupService.java
  src/main/java/kr/hs/mirim/family/service/UserService.java
Labels: 기능 : 회원/그룹 💡

#37 #16 회원이 로그인하는 기능
  src/main/java/kr/hs/mirim/family/controller/UserController.java
  src/main/java/kr/hs/mirim/family/dto/request/LoginUserRequest.java
  src/main/java/kr/hs/mirim/family/dto/response/LoginUserResponse.java
  src/main/java/kr/hs/mirim/family/entity/user/repository/UserRepository.java
  src/main/java/kr/hs/mirim/family/exception/BadRequestException.java
  src/main/java/kr/hs/mirim/family/service/GroupService.java
  src/main/java/kr/hs/mirim/family/service/UserService.java
Labels: 기능 : 회원/그룹 💡
