Repository re-prife/back-end, pull requests merged in 2022-05, with the labels that each got.

#31 #26 식재료 리스트 / 집안일 / 퀘스트 엔티티 생성
  src/main/java/kr/hs/mirim/family/FamilyApplication.java
  src/main/java/kr/hs/mirim/family/entity/BaseEntity.java
  src/main/java/kr/hs/mirim/family/entity/chore/Chore.java
  src/main/java/kr/hs/mirim/family/entity/chore/ChoreCategory.java
  src/main/java/kr/hs/mirim/family/entity/chore/ChoreCheck.java
  src/main/java/kr/hs/mirim/family/entity/group/Group.java
  src/main/java/kr/hs/mirim/family/entity/ingredient/Ingredient.java
  src/main/java/kr/hs/mirim/family/entity/ingredient/IngredientCategory.java
  src/main/java/kr/hs/mirim/family/entity/ingredient/IngredientSaveType.java
  src/main/java/kr/hs/mirim/family/entity/quest/Quest.java
  src/main/java/kr/hs/mirim/family/entity/user/User.java
Labels: 엔티티 🥚

#40 #36 그룹 API 리팩토링
  src/main/java/kr/hs/mirim/family/controller/GroupController.java
  src/main/java/kr/hs/mirim/family/dto/request/CreateGroupRequest.java
  src/main/java/kr/hs/mirim/family/dto/request/JoinGroupRequest.java
  src/main/java/kr/hs/mirim/family/service/GroupService.java
Labels: 기능 : 회원/그룹 💡, 리팩토링 ✍

#42 #9 심부름 전체 조회 기능
  src/main/java/kr/hs/mirim/family/controller/QuestController.java
  src/main/java/kr/hs/mirim/family/dto/response/QuestListResponse.java
  src/main/java/kr/hs/mirim/family/entity/quest/repository/QuestRepository.java
  src/main/java/kr/hs/mirim/family/service/GroupService.java
  src/main/java/kr/hs/mirim/family/service/QuestService.java
Labels: 기능 : 심부름💡

#43 #12 심부름 수락 및 수락 후 거절 기능
  src/main/java/kr/hs/mirim/family/controller/QuestController.java
  src/main/java/kr/hs/mirim/family/entity/quest/repository/QuestRepository.java
  src/main/java/kr/hs/mirim/family/entity/user/repository/UserRepository.java
  src/main/java/kr/hs/mirim/family/exception/ConflictException.java
  src/main/java/kr/hs/mirim/family/service/QuestService.java
  src/main/java/kr/hs/mirim/family/service/UserService.java
Labels: 기능 : 심부름💡

#45 #44 심부름 수락자가 심부름을 완료할 시 요청자가 완료 처리 기능 구현
  src/main/java/kr/hs/mirim/family/controller/QuestController.java
  src/main/java/kr/hs/mirim/family/dto/response/QuestListResponse.java
  src/main/java/kr/hs/mirim/family/entity/quest/repository/QuestRepository.java
  src/main/java/kr/hs/mirim/family/service/GroupService.java
  src/main/java/kr/hs/mirim/family/service/QuestService.java
Labels: 기능 : 심부름💡

#46 #3 식재료 추가 기능 구현
  src/main/java/kr/hs/mirim/family/controller/IngredientController.java
  src/main/java/kr/hs/mirim/family/dto/request/CreateIngredientRequest.java
  src/main/java/kr/hs/mirim/family/entity/ingredient/Ingredient.java
  src/main/java/kr/hs/mirim/family/entity/ingredient/IngredientCategory.java
  src/main/java/kr/hs/mirim/family/entity/ingredient/IngredientSaveType.java
  src/main/java/kr/hs/mirim/family/entity/ingredient/repository/IngredientRepository.java
  src/main/java/kr/hs/mirim/family/service/IngredientService.java
Labels: 기능 : 식재료 💡

#50 #38 각 하루별 집안일 당번 목록을 반환하는 기능
  src/main/java/kr/hs/mirim/family/controller/ChoreController.java
  src/main/java/kr/hs/mirim/family/dto/response/ChoreListOneDayDataResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/ChoreListOneDayResponse.java
  src/main/java/kr/hs/mirim/family/entity/chore/repository/ChoreRepository.java
  src/main/java/kr/hs/mirim/family/entity/chore/repository/ChoreRepositoryExtension.java
  src/main/java/kr/hs/mirim/family/entity/chore/repository/ChoreRepositoryImpl.java
  src/main/java/kr/hs/mirim/family/service/ChoreService.java
Labels: 기능 : 집안일 💡

#48 #47 식재료 전체 조회 기능 구현
  src/main/java/kr/hs/mirim/family/controller/IngredientController.java
  src/main/java/kr/hs/mirim/family/dto/response/IngredientListResponse.java
  src/main/java/kr/hs/mirim/family/entity/ingredient/Ingredient.java
  src/main/java/kr/hs/mirim/family/entity/ingredient/IngredientCategory.java
  src/main/java/kr/hs/mirim/family/entity/ingredient/IngredientSaveType.java
  src/main/java/kr/hs/mirim/family/entity/ingredient/repository/IngredientRepository.java
  src/main/java/kr/hs/mirim/family/entity/ingredient/repository/IngredientRepositoryExtension.java
  src/main/java/kr/hs/mirim/family/entity/ingredient/repository/IngredientRepositoryImpl.java
  src/main/java/kr/hs/mirim/family/service/IngredientService.java
Labels: 기능 : 식재료 💡

#53 #8 집안일 후 구성원에게 인증 요청을 보내는 기능
  src/main/java/kr/hs/mirim/family/controller/ChoreController.java
  src/main/java/kr/hs/mirim/family/entity/chore/repository/ChoreRepository.java
  src/main/java/kr/hs/mirim/family/service/ChoreService.java
Labels: 기능 : 집안일 💡

#54 #13 인증요청에 대한 응답을 처리하는 기능
  src/main/java/kr/hs/mirim/family/controller/ChoreController.java
  src/main/java/kr/hs/mirim/family/dto/request/ChoreCertifyReactionRequest.java
  src/main/java/kr/hs/mirim/family/service/ChoreService.java
Labels: 기능 : 집안일 💡

#55 #20 이달의 OO왕 기능 구현
  src/main/java/kr/hs/mirim/family/controller/KingController.java
  src/main/java/kr/hs/mirim/family/dto/response/KingDataResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/KingResponse.java
  src/main/java/kr/hs/mirim/family/entity/chore/repository/ChoreRepository.java
  src/main/java/kr/hs/mirim/family/entity/chore/repository/ChoreRepositoryExtension.java
  src/main/java/kr/hs/mirim/family/entity/chore/repository/ChoreRepositoryImpl.java
  src/main/java/kr/hs/mirim/family/service/KingService.java
Labels: 기능 : 왕 💡

#58 #18 회원을 탈퇴하는 기능
  src/main/java/kr/hs/mirim/family/controller/UserController.java
  src/main/java/kr/hs/mirim/family/dto/request/DeleteUserRequest.java
  src/main/java/kr/hs/mirim/family/exception/ForbiddenException.java
  src/main/java/kr/hs/mirim/family/service/UserService.java
Labels: 기능 : 회원/그룹 💡

#61 #60 회원 정보 수정을 위한 비밀번호를 인증하는 기능
  src/main/java/kr/hs/mirim/family/controller/UserController.java
  src/main/java/kr/hs/mirim/family/dto/request/CheckUserPasswordRequest.java
  src/main/java/kr/hs/mirim/family/service/UserService.java
Labels: 기능 : 회원/그룹 💡

#64 #19 회원이 자신의 정보를 수정하는 기능
  src/main/java/kr/hs/mirim/family/controller/UserController.java
  src/main/java/kr/hs/mirim/family/dto/request/UpdateUserRequest.java
  src/main/java/kr/hs/mirim/family/entity/user/User.java
  src/main/java/kr/hs/mirim/family/service/UserService.java
Labels: 기능 : 회원/그룹 💡

#62 #5 식재료 세부 사항 수정 기능 구현
  src/main/java/kr/hs/mirim/family/controller/IngredientController.java
  src/main/java/kr/hs/mirim/family/dto/request/IngredientRequest.java
  src/main/java/kr/hs/mirim/family/entity/ingredient/Ingredient.java
  src/main/java/kr/hs/mirim/family/service/IngredientService.java
Labels: 기능 : 식재료 💡

#66 #10 심부름 수정 기능 구현
  src/main/java/kr/hs/mirim/family/controller/QuestController.java
  src/main/java/kr/hs/mirim/family/dto/request/QuestRequest.java
  src/main/java/kr/hs/mirim/family/dto/response/QuestResponse.java
  src/main/java/kr/hs/mirim/family/entity/quest/Quest.java
  src/main/java/kr/hs/mirim/family/service/QuestService.java
Labels: 기능 : 심부름💡

#74 #14 집안일 삭제 기능
  src/main/java/kr/hs/mirim/family/controller/ChoreController.java
  src/main/java/kr/hs/mirim/family/service/ChoreService.java
Labels: 기능 : 집안일 💡

#75 #73 식재료 일괄 삭제 기능 구현
  src/main/java/kr/hs/mirim/family/controller/IngredientController.java
  src/main/java/kr/hs/mirim/family/dto/request/DeleteIngredientDataRequest.java
  src/main/java/kr/hs/mirim/family/dto/request/DeleteIngredientRequest.java
  src/main/java/kr/hs/mirim/family/service/IngredientService.java
Labels: 기능 : 식재료 💡

#72 #67 이달의 왕 계산 기능 구현
  src/main/java/kr/hs/mirim/family/controller/KingController.java
  src/main/java/kr/hs/mirim/family/dto/response/ChoreKingResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/KingDataResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/KingResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/QuestKingResponse.java
  src/main/java/kr/hs/mirim/family/entity/chore/repository/ChoreRepositoryExtension.java
  src/main/java/kr/hs/mirim/family/entity/chore/repository/ChoreRepositoryImpl.java
  src/main/java/kr/hs/mirim/family/entity/quest/repository/QuestRepository.java
  src/main/java/kr/hs/mirim/family/entity/quest/repository/QuestRepositoryExtension.java
  src/main/java/kr/hs/mirim/family/entity/quest/repository/QuestRepositoryImpl.java
  src/main/java/kr/hs/mirim/family/service/KingService.java
Labels: 기능 : 왕 💡, 기능 : 심부름💡

#79 #71 회원 상세 정보 수정 관련 기능 수정
  src/main/java/kr/hs/mirim/family/controller/UserController.java
  src/main/java/kr/hs/mirim/family/dto/request/UpdateUserPasswordRequest.java
  src/main/java/kr/hs/mirim/family/dto/request/UpdateUserRequest.java
  src/main/java/kr/hs/mirim/family/entity/user/User.java
  src/main/java/kr/hs/mirim/family/service/UserService.java
Labels: 기능 : 회원/그룹 💡, 리팩토링 ✍

#80 #65 심부름 리팩토링
  src/main/java/kr/hs/mirim/family/dto/response/QuestResponse.java
  src/main/java/kr/hs/mirim/family/entity/quest/repository/QuestRepository.java
  src/main/java/kr/hs/mirim/family/service/QuestService.java
Labels: 기능 : 심부름💡, 리팩토링 ✍

#90 #83 집안일 날짜 관련 기능 수정
  src/main/java/kr/hs/mirim/family/controller/ChoreController.java
  src/main/java/kr/hs/mirim/family/dto/request/ChoreCertifyReactionRequest.java
  src/main/java/kr/hs/mirim/family/entity/chore/repository/ChoreRepository.java
  src/main/java/kr/hs/mirim/family/exception/DateOverException.java
  src/main/java/kr/hs/mirim/family/service/ChoreService.java
Labels: 기능 : 집안일 💡

#92 #89 스웨거 연동
  build.gradle
  src/main/java/kr/hs/mirim/family/config/SwaggerConfig.java
  src/main/java/kr/hs/mirim/family/controller/ChoreController.java
  src/main/java/kr/hs/mirim/family/controller/GroupController.java
  src/main/java/kr/hs/mirim/family/controller/IngredientController.java
  src/main/java/kr/hs/mirim/family/controller/KingController.java
  src/main/java/kr/hs/mirim/family/controller/QuestController.java
  src/main/java/kr/hs/mirim/family/controller/UserController.java
  src/main/java/kr/hs/mirim/family/dto/request/ChoreCertifyReactionRequest.java
  src/main/java/kr/hs/mirim/family/dto/request/CreateChoreRequest.java
  src/main/java/kr/hs/mirim/family/dto/request/CreateGroupRequest.java
  src/main/java/kr/hs/mirim/family/dto/request/CreateUserRequest.java
  src/main/java/kr/hs/mirim/family/dto/request/DeleteIngredientDataRequest.java
  src/main/java/kr/hs/mirim/family/dto/request/DeleteIngredientRequest.java
  src/main/java/kr/hs/mirim/family/dto/request/DeleteUserRequest.java
  src/main/java/kr/hs/mirim/family/dto/request/IngredientRequest.java
  src/main/java/kr/hs/mirim/family/dto/request/JoinGroupRequest.java
  src/main/java/kr/hs/mirim/family/dto/request/LoginUserRequest.java
  src/main/java/kr/hs/mirim/family/dto/request/QuestRequest.java
  src/main/java/kr/hs/mirim/family/dto/request/ReportRequest.java
  src/main/java/kr/hs/mirim/family/dto/request/UpdateIngredientCountDataRequest.java
  src/main/java/kr/hs/mirim/family/dto/request/UpdateIngredientCountRequest.java
  src/main/java/kr/hs/mirim/family/dto/request/UpdateUserPasswordRequest.java
  src/main/java/kr/hs/mirim/family/dto/request/UpdateUserRequest.java
  src/main/java/kr/hs/mirim/family/dto/response/ChoreKingResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/ChoreListDataResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/ChoreListOneDayResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/IngredientListResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/KingResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/LoginUserResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/QuestKingResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/QuestResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/UserFindKingResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/UserFindResponse.java
  src/main/java/kr/hs/mirim/family/dto/response/UserListResponse.java
Labels: 문서 📄

#95 #94 식재료 에러 처리 추가
  src/main/java/kr/hs/mirim/family/service/GroupService.java
  src/main/java/kr/hs/mirim/family/service/IngredientService.java
Labels: 기능 : 식재료 💡

#98 #97 codecov 관련 gradle 추가, test 디렉토리 yml 파일 추가
  build.gradle
  src/test/resources/application.yml
  src/test/resources/data.sql
Labels: 테스트 💯, 세팅 ⚙
